export { AboutPage } from './about'
export { ContactsPage } from './contacts'
export { CoursesPage } from './courses'
export { DevelopmentPage } from './development'
export { EducationPage } from './education'
export { HomePage } from './home'
export { MentoringPage } from './mentoring'
export { NotFoundPage } from './not-found'
export { PrivacyPage } from './privacy'
export { ProjectsPage } from './projects'
export { ResumePage, ResumeRolePage } from './resume'
